spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cl?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 879730923
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: never   # 这行是关键！禁用数据库初始化检测

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

server:
  port: 8080